//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_in_C_Sharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EarningReport
    {
        public int @int { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public string Fees { get; set; }
        public string SalaryPaid { get; set; }
        public string Internet { get; set; }
        public string Gas { get; set; }
        public string Electricity { get; set; }
        public string Mess { get; set; }
    }
}
