//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_in_C_Sharp
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int id { get; set; }
        public string name { get; set; }
        public string father_name { get; set; }
        public Nullable<int> age { get; set; }
        public string cnic { get; set; }
        public string mobile { get; set; }
        public string address_per { get; set; }
        public string relationship { get; set; }
        public string mobile_emr { get; set; }
        public string address_emr { get; set; }
        public string roomno { get; set; }
        public string allot_date { get; set; }
        public string admission_fees { get; set; }
        public string fees { get; set; }
        public string default_dues { get; set; }
        public Nullable<bool> fees_status { get; set; }
        public string name_emr { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
